language: go
go:
- 1.9
- master
notifications:
  slack:
    secure: PAOkvw8Qjljs2uJ7gaXSYkn/fAelGm/498Fyz9oPKisxO7kspj69rpgQmXIXsLvnh6IKK1EJ977v4lkw1CYyu9bkcXZ7cGkqcxTDq54W5mbGPZa8WiJ/fw80lTqdchil2psav24OBnzrTP9kd4t8RkS3ZdS4GDSyOk5lWTYzjc4tkcpUEf7sDwC0QTNT+Oaz9CU5x952FBUQ8eBoCwhLyrWMUI9mjYdN8ERolzSzS1fmyKPtkhNkbhuH3hJlCcJJV0IgoUcRPxDJAtJFYZn3/+5TqHmmZDGeQYTBrVrxj3AWNllDLwCXuIvxiA61ZSgdY6R9ya11HG1wQvs6OaEtX3x9hDttZ0o0/yjSdvT2r2C/7LVkbOKmvTH3iBTuzT53GhfggKz8fU0MDbCODMMHKoU0oAdh0wqFVbHvwDKngPSg/ryabYkfIIj7Ooj5p/LmUx0j7M2NJ+ERTIXGcrKF9CY67973lu39F94me6eGzGuZ/dDeSZtPN3vzuM1klXbmWLpT+Ik27r/x87gI735IV0/RYLULXex3Ij/IwZMVsLtHRIX2fxr+PMCo4cYqP6wyEnnoJ2BMkNeVvvw/FYOznBc/9a92RzOXvHgcNuS6OhQwH6W7VypzuH/oSf7x6QI5ZpflU5FYx6Mv8pcnFNEU1j+Y6itMuxGA4dppoMfkN3U=
