
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "*"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "*"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "*"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "*"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "*"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "*"
  
[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "*"
