
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "*"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "*"

[[constraint]]
  name = "github.com/shurcooL/githubql"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"