
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "*"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "*"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "*"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "*"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "*"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "v1.3.1"
<<<<<<< HEAD
  
=======

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

>>>>>>> 79f27f76d884bd4d91f8fb9ddd5659ff723bdfbc
[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "*"

[[constraint]]
  name = "github.com/shurcooL/githubql"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"