// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "ocg": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/aweisser/ocg-poc/io/rest/design
// --out=$(GOPATH)\src\github.com\aweisser\ocg-poc\io\rest\
// --version=v1.1.0-dirty

package app

import (
	"fmt"
	"strings"
)

// MemberHref returns the resource href.
func MemberHref(memberID interface{}) string {
	parammemberID := strings.TrimLeftFunc(fmt.Sprintf("%v", memberID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/members/%v", parammemberID)
}
